name: Metrics

on:
  schedule:
    - cron: "0 0 * * *" # roda todo dia à meia-noite
  workflow_dispatch: # permite rodar manualmente

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.PAT_1 }}
          user: MathiasFilypeDev
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Sao_Paulo

          # Linguagens
          plugin_languages: yes
          plugin_languages_limit: 10
          plugin_languages_sections: most-used, recently-used
          plugin_languages_indepth: yes

          # Seguidores e follow-up
          plugin_followup: yes
          plugin_followup_sections: repositories, user

          # Estrelas recebidas
          plugin_stargazers: yes
          plugin_stargazers_charts: yes
          plugin_stargazers_charts_type: classic

          # Hábitos de contribuição
          plugin_habits: yes
          plugin_habits_days: 30
          plugin_habits_facts: yes
          plugin_habits_charts: yes
